// Program to use stepper motor with arduino via A4988 driver

// Pin Definitions
const int dirPin = 2;
const int stepPin = 3;
const int stepsPerRevolution = 200;

void setup()
{
	// Declare pins as Outputs
	pinMode(stepPin, OUTPUT);
	pinMode(dirPin, OUTPUT);
}
void loop()
{
  digitalWrite(dirPin, HIGH);

  // Manually generating PWM pulses. The PWM signal generated by arduino doesn't work for some reason
	for(int x = 0; x < stepsPerRevolution*5; x++)
	{
		digitalWrite(stepPin, HIGH);
		delayMicroseconds(700);
		digitalWrite(stepPin, LOW);
		delayMicroseconds(700);
	}
  digitalWrite(dirPin, LOW);
	for(int x = 0; x < stepsPerRevolution*5; x++)
	{
		digitalWrite(stepPin, HIGH);
		delayMicroseconds(700);
		digitalWrite(stepPin, LOW);
		delayMicroseconds(700);
	}
}